name: Run Newman Tests and Save HTML Report

on:
  push:
    branches:
      - main  # Define la rama de GitHub que activará este flujo de trabajo

jobs:
  newman_test:
    runs-on: ubuntu-latest  # Especifica el sistema operativo en el que se ejecutará

    steps:
      - name: Checkout repository  # Paso para clonar el repositorio
        uses: actions/checkout@v2

      - name: Create reports directory  # Crear directorio "reports" en la raíz del proyecto
        run: mkdir -p ${GITHUB_WORKSPACE}/reports

      - name: Set up Node.js  # Instala Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Versión de Node.js que deseas usar

      - name: Install Newman and Newman HTML reporter  # Instala Newman y el reportero HTML
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Newman and save HTML report  # Ejecuta Newman y guarda el reporte HTML
        run: |
          newman run NewCollection.postman_collection.json -r html --reporter-html-export ${GITHUB_WORKSPACE}/reports/reporte.html
          ls -l ${GITHUB_WORKSPACE}/reports  # Listar archivos en el directorio reports para verificar

      - name: Display reporte.html content  # Mostrar el contenido del archivo reporte.html para depuración
        run: |
          cat ${GITHUB_WORKSPACE}/reports/reporte.html

      - name: Upload HTML report artifact  # Subir el reporte HTML como un artefacto
        if: success()  # Subir el reporte HTML solo si el paso anterior tiene éxito
        uses: actions/upload-artifact@v2
        with:
          name: newman-html-report  # Nombre del artefacto que se muestra en GitHub Actions
          path: ${GITHUB_WORKSPACE}/reports/reporte.html  # Ruta al reporte HTML que se subirá como artefacto
