name: Run Newman Tests and Save HTML Report

on:
  push:
    branches:
      - main  # Define la rama de GitHub que activar치 este flujo de trabajo

jobs:
  newman_test:
    runs-on: ubuntu-latest  # Especifica el sistema operativo en el que se ejecutar치

    steps:
      - name: Checkout repository  # Paso para clonar el repositorio
        uses: actions/checkout@v2

      - name: Set up Node.js  # Instala Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Versi칩n de Node.js que deseas usar

      - name: Install Newman and Newman HTML reporter  # Instala Newman y el reportero HTML
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Newman and save HTML report
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/report
          newman run NewCollection.postman_collection.json -r html --reporter-html-export ${GITHUB_WORKSPACE}/report/reporte.html > /dev/null 2>&1

      - name: Upload HTML report artifact  # Sube el reporte HTML como un artefacto
        uses: actions/upload-artifact@v2
        with:
          name: newman-html-report  # Nombre del artefacto que se muestra en GitHub Actions
          path: ${GITHUB_WORKSPACE}/report/reporte.html  # Ruta al reporte HTML que se subir치 como artefacto
